name: Publish to NPM

on:
  release:

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Test cli
        run: bun packages/cli/dist/cli.js --version

      - name: Publish cli to NPM
        run: bun publish packages/cli
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Test core
        run: |
          echo "import('./packages/core/dist/index.js').then((mod) => {
            if (typeof mod.defineWorkflow !== 'function')
              throw new Error('Smoke test failed');
            console.log('smoke OK (esm)');
          });" | bun run -

      - name: Publish core to NPM
        run: bun publish packages/core
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
